### ISSUE TITLE
achievements?

### ISSUE THREAD

**Issue by dcsan** [mulhoon/score.js#4]
wonder if you handle discrete achievements?
or can recommend another lib?

this just seems for levelled scoring.

**Comment by mulhoon** [comment]
HI @dcsan, 
Can you explain a bit more about discrete achievements. What are they? and how would you want to use them?

Thanks

**Comment by dcsan** [comment]
hi - 

`discrete` as in one off, not related to levelling.

like a badge you get that can be triggered with a one liner, its not based on levelling up. that allows random badges to be assigned based on in-game events/logic, like finding an item, or logging in three days in a row.

at first load the Badge lib would read a config file like

```
badges:
  - name: newbie
    imagePath: /badges/newbie.png
    short: Get this when you start the game
  - name: explorer
    imagePath: /badges/explorer.png
    short: Get this when you find stuff
```


```js
const badges = new BotBadges('userid-1234') // pass in unique id

badges.get('explorer') // add a new badge by name (or maybe later by an ENUM value)
badges.list() // show list per user
```

then later
```
badges.render() // render a single PNG showing that user's badges
```

It might be nice to extend this eg so you need to hit that badge three times to "master" the achievement but that's another extension.

also is your code DB backed?
and it seems to depend on `window` - does it run server side too?
